// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvuRJXTajVlnhrLsTQK_wwuu7s_Z4my8',
    appId: '1:1017623795055:web:d220d48bd2cfd14497449a',
    messagingSenderId: '1017623795055',
    projectId: 'pvi-nhm',
    authDomain: 'pvi-nhm.firebaseapp.com',
    storageBucket: 'pvi-nhm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96fZAFeL6OTmbvPmE1h0VqhLlcFp1JsM',
    appId: '1:1017623795055:android:2e839aaab4e3b47c97449a',
    messagingSenderId: '1017623795055',
    projectId: 'pvi-nhm',
    storageBucket: 'pvi-nhm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2X_jE9YKJb3WmJHDtTSkl3tVJpcfAH0',
    appId: '1:1017623795055:ios:3c980f5c744f5a0197449a',
    messagingSenderId: '1017623795055',
    projectId: 'pvi-nhm',
    storageBucket: 'pvi-nhm.appspot.com',
    iosBundleId: 'com.example.pviNhm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2X_jE9YKJb3WmJHDtTSkl3tVJpcfAH0',
    appId: '1:1017623795055:ios:3c980f5c744f5a0197449a',
    messagingSenderId: '1017623795055',
    projectId: 'pvi-nhm',
    storageBucket: 'pvi-nhm.appspot.com',
    iosBundleId: 'com.example.pviNhm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARvuRJXTajVlnhrLsTQK_wwuu7s_Z4my8',
    appId: '1:1017623795055:web:aa3923af8eb3381897449a',
    messagingSenderId: '1017623795055',
    projectId: 'pvi-nhm',
    authDomain: 'pvi-nhm.firebaseapp.com',
    storageBucket: 'pvi-nhm.appspot.com',
  );
}
